name: CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Profile
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            echo "PROFILE=dev" >> $GITHUB_ENV
            echo "BRANCH=dev" >> $GITHUB_ENV
            echo "AWS_HOST=${{ secrets.DEV_AWS_EC2_HOST }}" >> $GITHUB_ENV
            echo "AWS_USER=${{ secrets.DEV_AWS_EC2_USER }}" >> $GITHUB_ENV
            echo "AWS_KEY=${{ secrets.DEV_AWS_EC2_KEY }}" >> $GITHUB_ENV
          else
            echo "PROFILE=prd" >> $GITHUB_ENV
            echo "BRANCH=main" >> $GITHUB_ENV
            echo "AWS_HOST=${{ secrets.AWS_EC2_HOST }}" >> $GITHUB_ENV
            echo "AWS_USER=${{ secrets.AWS_EC2_USER }}" >> $GITHUB_ENV
            echo "AWS_KEY=${{ secrets.AWS_EC2_KEY }}" >> $GITHUB_ENV
          fi

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ env.AWS_EC2_HOST }}
          username: ${{ env.AWS_EC2_USER }}
          key: ${{ env.AWS_EC2_KEY }}
          port: 22
          script: |
            git pull origin $BRANCH && docker compose down && docker compose up -d --build
